version: "3.7"

services:
  reverse_proxy:
    build: 
      context: proxy/
      dockerfile: Dockerfile
      args:
        - PUID=1000
        - PGID=1000
        - USER=proxyuser
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./secrets/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
  bioz:
    container_name: bioz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUID=1000
        - PGID=1000
        - USER=dockeruser
    env_file:
      - .env
    user: dockeruser
    volumes:
      - ./logs/bioz:/logs/bioz
      - ./secrets:/secrets
    restart: always